### ISSUE TITLE
Cannot run this tool correctly

### ISSUE THREAD

**Issue by DamonLiuTHU** [ashutosh0gupta/TARA#1]
I and using Ubuntu 14 and built TARA successfully, but after that I can't run any example code correctly, and always encounter the same problem: Assertion 'false' failed. Aborted(core dumped).
I don't know if it's the problem of my machine or a bug in TARA. Pls help.

**Comment by ashutosh0gupta** [comment]
Can you compile in Debug mode (May take half an hour and several GBs of memory) and report the error message?

**Comment by DamonLiuTHU** [comment]
Yes, I've compiled it in debug mode successfully, but have to comment a line of code(assert(false)) before compile. Still the compiled tara executable reported "segmentation fault" when running one of the c++ code in example folder.
The command line I ran is  `./tara -M rmo --print=prune,rounds,output,phi --mode=synthesis ./example/c/rmo-ctrl-dep-1.cpp`
I don't know the reason, is it because of lack of memory or anything else?

**Comment by ashutosh0gupta** [comment]
This is absolutely embarrassing. We have two mode in our tool "synthesis" and "fsynth". synthesis is the old method from our POPL 2015 paper. We are replacing it with the fsynth method. We have kept the old method for backward compatibility with our other tools. fsynth is the one that works with weak memory models.

Please try the following command:

   ./tara -M rmo --mode=fsynth ./examples/c/rmo-ctrl-dep-1.cpp

Let me know if this solves the problem.

**Comment by DamonLiuTHU** [comment]
That solved my confusion, thanks a lot! 💯
